- tests/dbgutil.c
- tests/dbgutil.h
Before this patch check_if_png() comment was kind of misleading because
it talked about the behaviour of png_sig_cmp() which isn't the same as
check_if_png().
> check_if_png: clarify comments.

- lib/identify.c
- lib/quirc.c
- lib/quirc_internal.h
(another) attempt to fix #2:
This patch makes large images support a compile time option by
allowing `QUIRC_MAX_REGIONS` to be tuned via CFLAGS up to 65534 (current
default is 254).
Implementation
---------------------
I took a different approach than #3 while allowing to keep a low memory footprint for embedded systems.
In #3, the detection code is working directly on `q->image` (as it is the case today in master), and `sizeof(*q->image)` depends on `QUIRC_MAX_REGIONS` value. I see at least two issues with this method, both related to the fact that `q->image` is "leaked" to the library caller.
1. The caller is responsible to "convert" the image bytes to `quirc_pixel_t` (see for example https://github.com/dlbeer/quirc/pull/3/files#diff-79a52e3b6de15a145f24844878b809e2). The convertion is …
> Large images decoding support

- tests/dbgutil.c
support for PNG files using palette, like this one:
> PNG_COLOR_TYPE_PALETTE support for inspect and qrtest.

- tests/dbgutil.c
Show a human readable Data type description, before:
```
Decode successful:
Version: 1
ECC level: L
Mask: 2
Data type: 4
Length: 5
Payload: plouf
```
after
```
Decode successful:
Version: 1
ECC level: L
Mask: 2
Data type: 4 (BINARY)
Length: 5
Payload: plouf
```
> dump_data: display a human readable Data type.

- tests/dbgutil.c
New versions of libpng lack `png_infopp_NULL`.
> Fix compatibility with newer libpng

- demo/camera.c
In OpenBSD *video4linux2* API is available in `<sys/videoio.h>` header, not in `<linux/videodev2.h>` as in Linux or FreeBSD.  Detection relies on `__OpenBSD__` macro, which shouldn't be defined on other platforms.
> Fix V4L2 includes on OpenBSD

- tests/dbgutil.c
Forgot one instance of `png_infopp_NULL`.  This should have been part of 176ba28362bc0a84a052306f677bb4af91a0fa72 (PR #12).
> Replaced remaining instance of png_infopp_NULL

- .gitignore
- Makefile
These changes allow building quirc on BSDs (namely OpenBSD).  While at it, I added several unrelated improvements:
* allow overriding default compiler flags and providing additional linker flags,
* use PIC objects for static library as well (instead of building a separate set of non-PIC objects),
* instead of hard-coding shared library name with `-Wl,-soname=` just compile it with proper name.
This PR also drops symlinks for shared library.
> Make Makefile compatible with BSD make

- tests/qrtest.c
This is a cosmetic change fixing my own fault: in c13db788bbd4ee30fed90ae56acf14f7527b2b17 I switched `clock_t` variables in `scan_file()` function to `long`, but I forgot to switch them to `unsigned int` in 1de1a466b882011fcb28c29077ce392c4b3b238c.  I don't think they can overflow, but for the sake of correctness they should be switched as well.
> Consistant typing for test timing variables

- tests/dbgutil.c
Changes:
* more accurate bit depth reduction.
* fix handling of images with `tRNS` chunk.
First one is a drive-by fix.  Second is the one I care for because it allows feeding `qrtest` with images generated by [`qrencode` tool](http://fukuchi.org/works/qrencode/).
> Fix png image handling

- lib/identify.c
Before this patch, small images (i.e. 7x7 pixels or less) could trigger
SIGFPE because of a (integer) division by zero.
see #20
> Avoid division by zero.

- lib/identify.c
Fix the following warning when compiling with GCC 6:
lib/identify.c: In function ‘quirc_end’:
lib/identify.c:430:6: warning: ‘last_color’ may be used uninitialized in this function [-Wmaybe-uninitialized]
int last_color;
^~~~~~~~~~
> identify: fix warning

- lib/decode.c
Before this patch, Kanji decoding was broken.
To ease the eyes, a trivial patch is needed for `tests/dbgutil.c`:
https://gist.github.com/kAworu/e066f1c8f2f00aadc3e6ac48ff937ea9
The test image is a simple QR Code (version=1,level=L,mode=KANJI) created with https://github.com/kAworu/node-quirc/blob/master/test/data/generated/qrgen.c,
The payload is `kanji_data[4] = {0x93, 0x5f,0xe4, 0xaa}; /* 点茗 in Shift-JIS */`
```
% ./inspect version=01,level=L,mode=KANJI.png 
quirc inspection program
Copyright (C) 2010-2012 Daniel Beer <dlbeer@gmail.com>
Library version: 1.0
1 QR-codes found:
21 cells, corners: (12,12) (75,12) (75,75) (12,75)
[][][][][][][]      []  []  [][][][][][][]
[]          []          []  []          []
[]  [][][]  []  []  []      []  [][][]  []
[]  [][][]  []          []  [] …
```
> Fix Kanji decoding.

- lib/quirc.c
- lib/quirc.h
This is a preparation patch before removing the use of VLA.
The commit message should be enough to understand the rational of the patch.
Alternatively, I believe that the state of `q` could be made consistent by safely using the minimum values for both `q->w` and `q->h`:
```c
q->h = MIN(q->h, h);
q->w = MIN(q->w, w);
```
but I feel that's over-engeneering code for a corner case. Correct me if I'm wrong.
> Fix a potential use-after-free on quirc_resize failure.

- demo/mjpeg.c
- lib/identify.c
- lib/quirc.c
- lib/quirc_internal.h
PR to avoid using c99 VLA as discussed on https://github.com/dlbeer/quirc/issues/36#issuecomment-306399797.
I wrote a [Coccinelle](http://coccinelle.lip6.fr/) semantic patch to track them down (see [here](https://gist.github.com/kAworu/14910868052bb248e55ea73802f45d5b), it's not perfect but fine enough for our case).
```
% spatch -I /usr/include -I /usr/local/include -I . -sp_file vla.cocci .           
init_defs_builtins: /usr/lib/coccinelle/standard.h
HANDLING: ./demo/convert.c
HANDLING: ./demo/demo.c
HANDLING: ./demo/camera.c
HANDLING: ./demo/scanner.c
HANDLING: ./demo/demoutil.c
HANDLING: ./demo/dthash.c
HANDLING: ./demo/mjpeg.c
* TODO [[view:./demo/mjpeg.c::face=ovl-face1::linb=228::colb=10::cole=13][./demo/mjpeg.c::228]]
HANDLING: ./tests/qrtest.c
HANDLING: ./tests/dbgutil.c …
```
> Refactoring to remove the use of c99 VLA

- demo/mjpeg.c
Before this patch the `rgb` pointer was incremented by the "inner" for
loop but never reset to the start of the buffer by the "outer" while
loop.
This bug was introduced by the refactoring in
6158aeb30ad4b81519ee69482066c0b3c3d7b10d.
> fix mjpeg_decode_rgb32().

- lib/identify.c
- lib/quirc.c
- lib/quirc_internal.h
Hi Daniel
I replaced the existing threshold function with another one based on [Otsu's algorithm](https://en.wikipedia.org/wiki/Otsu%27s_method). Not only does this improve the overall quality of QR code detection, the whole detection process is also considerably faster. On my Intel desktop system detection time improved by a factor of 2.5 on average (even more for images with a lot of noise or bad lighting).
Would you mind having a look at my pull request?
Regards,
Claudio
**Example**
*Original image:*
*Binarization with old threshold function:*
*Binarization with new Otsu-based threshold function:*
> Replaced existing threshold function with Otsu threshold algorithm

- lib/identify.c
- lib/quirc.c
- lib/quirc_internal.h
Before this patch, the "sizeof dance" was confusing, fix #54.
> define a QUIRC_PIXEL_ALIAS_IMAGE constant to explicit conditional path

- lib/identify.c
Fixes #68
Using `UINT8_MAX` here explicit that any `uint8_t` value is a valid index in the `histogram` array. Looping over the `uint8_t` range make it obvious that `threshold = i` is safe.
> Refactored some c99 features

- tests/inspect.c
Compiler gives this warning because an integer can take up more space
tests/inspect.c:155:3: note: ‘snprintf’ output between 4 and 13 bytes into a destination of size 8
snprintf(buf, sizeof(buf), "%d.%c", index, "ABC"[i]);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Fix compiler warning

- .gitignore
- README.md
- lib/decode.c
- lib/identify.c
- lib/quirc.h
- tests/inspect.c
- tests/qrtest.c
The QR-code specification supports various optional features. A newer one is "mirror imaging". I don't know in which version of the specification (2006, 2009 or 2015) it was added, but it certainly is mentioned in ISO 18004:2015:
ISO 18004: 2015, page 6, "*Mirror lmaging*":
> The arrangement of modules defined in this International Standard represents the "normal"
> orientation of the symbol. lt ls, however, possible to achieve a valid decode of a symbol in which the
> arrangement of the modules has been laterally transposed. When viewed with the finder patterns
> at the top left, top right and bottom left corners of the symbol, the effect of mirror imaging is to
> interchange the row and column positions of the modules.
ISO 18004: 2015, page 62, "*Decoding procedure overview*":
> …
> 2. …
> Support horizontally flipped QR-codes according to ISO 18004:2015

- Makefile
- demo/demo_opencv.cxx
- demo/demoutil.h
- demo/dthash.h
My motivation is to experiment quirc on macOS, where
neither of SDL1 or V4L2 work.
```
% brew install opencv
% brew install pkg-config
% brew install bsdmake
% bsdmake quirc-demo-opencv
% ./quirc-demo-opencv
```
Note: the macOS version of GNU make (/usr/bin/make) is a bit old
for quirc's Makefile.
> quirc-demo-opencv: Add OpenCV version of the demo

- lib/identify.c
When using small captured images, I somehow frequently see failures
to recognize a capstone due to rounding errors.
eg. when pb[] = {2 3 8 3 2}.
This commit tries to improve it by using fixed-point arithmetics.
The scaling factor was chosen somehow arbitrary. A moderate scaling
should be enough.
> finder_scan: Improve capstone detection on small images

- lib/identify.c
- lib/quirc.c
- lib/quirc_internal.h
* Make flood filling logic iterative (vs recursive)
I basically tried one-to-one conversions here to avoid mistakes.
probably it has a room for later optimizations.
* Use explicit malloc (vs variables on stack) to allocate the work area.
* Estimate the amount of memory for the work area dynamically
from the image size, instead of using a constant FLOOD_FILL_MAX_DEPTH,
which is too big in the most cases.
> Improve stack usage for flood filling

- README.md
- lib/identify.c
- lib/quirc_internal.h
On some platforms, such as microcontrollers with a single-precision FPU, operations on double type can be significantly slower compared to the float type. For example, on an ESP32-S3 microcontroller, decoding a QR code of a certain size may take 1700ms when 'double' is used and just 250ms when 'float' is used, ~6 times faster.
This commit adds two options to allow for such optimizations:
- `QUIRC_FLOAT_TYPE`: if defined, it is the type name to use in floating point calculations. Can be set, for example, using: `CFLAGS += -DQUIRC_FLOAT_TYPE=float`
- `QUIRC_USE_TGMATH`: if defined, Quirc will internally use `<tgmath.h>` header, instead of `<math.h>`. This C99-or-later header allows the program to call [type-generic functions](https://en.cppreference.com/w/c/numeric/tgmath), such as `sqrt`, …
> Add an option to use single-precision floating point in calculations

- README.md
`README.md` claims the software is BSD-licensed, but `LICENSE` is ISC. While some might validly consider the ISC license to belong to the BSD family, the apparent discrepancy is confusing. This PR adjusts `README.md` to say the software is ISC-licensed instead.
> Correct README.md to match LICENSE

- lib/identify.c
I was checking out what's new and noticed @igrr 's float customization work, but also noticed that it was missing the static casting of constants, which at least GCC is missing (perhaps it could optimize with `-ffast-math`).
I also took the liberty of changing repetitive divisions by the same value, to use of the reciprocal of the value.
I validated that there were no more unwanted double stuff on my x86 station as well as with:
```sh
make \
CC="arm-none-eabi-gcc" \
CFLAGS="-DQUIRC_USE_TGMATH -D QUIRC_FLOAT_TYPE=float -mthumb -Os"
```
In this configuration, these changes are shaving off a whopping 51 bytes from the code size!
Note: This contribution was minimally tested  and unreviewed.
> More quirc_float_t
